# Important Notes:
# Every field you add must be added to build-logic/src/main/kotlin/multiloader-common.gradle expandProps map.

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Project
version=1.1.0
group=com.wfphantom.redstonequill
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Redstone Quill
mod_id=redstonequill
license=MIT
description=Adds a redstone quill item that lets you write redstone on the walls!
minecraft_version_range=[1.21.1]
## This is the version of minecraft that the 'common' project uses. You can find a list of all versions here
## see https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# Optional
mod_authors=WFPhantom
credits=wilechaote, Poly_0000
issue_tracker=https://github.com/WFPhantom/redstonequill/issues
homepage=https://modrinth.com/mod/redstone-quill
logo=assets/redstonequill/logo.png

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=21.1.248
# ModDevGradle, see https://projects.neoforged.net/neoforged/moddevgradle for new versions
mdg_version=2.0.143
# Optional, see https://docs.neoforged.net/docs/misc/updatechecker/
update_json_url=https://api.modrinth.com/updates/redstone-quill/forge_updates.json?neoforge=only

# Fabric Dependencies (optional)
fabric_api_version=0.116.14+1.21.1
#fabric_kotlin_version=1.13.13+kotlin.2.4.10

# Neo Dependencies (optional)
#neo_kotlin_version=
jade_version = 15.10.5